"use client";

import { useEffect, useState } from "react";
import { getVaultSummary, type VaultSummary } from "@/lib/services/vault";

export default function ProductCard() {
  const [data, setData] = useState<VaultSummary | null>(null);
  const [open, setOpen] = useState(false);

  useEffect(() => {
    getVaultSummary().then(setData).catch(() => setData(null));
  }, []);

  return (
    <div className="rounded-xl border p-6 bg-background/60 backdrop-blur">
      <div className="flex items-center justify-between">
        <h2 className="text-xl font-semibold">Ajey Vault</h2>
        <button
          className="text-sm px-3 py-1 rounded-md border"
          onClick={() => setOpen((v) => !v)}
        >
          {open ? "Hide" : "Details"}
        </button>
      </div>
      <div className="mt-3 grid grid-cols-3 gap-4 text-sm">
        <div>
          <div className="text-muted-foreground">Total Assets</div>
          <div>${data?.totalAssetsUSD?.toLocaleString() ?? "—"}</div>
        </div>
        <div>
          <div className="text-muted-foreground">NAV / Share</div>
          <div>{data?.navPerShare ?? "—"}</div>
        </div>
        <div>
          <div className="text-muted-foreground">vToken Supply</div>
          <div>{data?.vTokenSupply ?? "—"}</div>
        </div>
      </div>

      {open && (
        <div className="mt-4">
          <p className="text-sm text-muted-foreground">
            Yield is generated by supplying idle assets to Aave v3. Vault shares track value via ERC‑4626 exchange rate.
          </p>
          <div className="mt-3 grid md:grid-cols-3 gap-3">
            {data?.strategies?.map((s) => (
              <div key={s.id} className="rounded-lg border p-3">
                <div className="text-sm font-medium">{s.name}</div>
                <div className="text-xs text-muted-foreground">{s.allocationPct}% allocated</div>
                <div className="text-xs">APR {s.aprPct}%</div>
              </div>
            ))}
          </div>
        </div>
      )}

      <div className="mt-4 flex items-center gap-2">
        <input
          type="number"
          placeholder="Amount"
          className="w-40 rounded-md border bg-background px-3 py-2 text-sm"
        />
        <button className="rounded-md border px-4 py-2 text-sm">Deposit</button>
      </div>
    </div>
  );
}


